//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kk
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расчет.
    /// </summary>
    // *** Start programmer edit section *** (Расчет CustomAttributes)

    // *** End programmer edit section *** (Расчет CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("Расчет", new string[] {
            "Код as \'Код\'",
            "Дата as \'Дата\'",
            "Сотрудники.Фио as \'ФИО\'",
            "Сотрудники.Должности.Наименование as \'Должность\'"}, Hidden=new string[] {
            "Сотрудники.Фио"})]
    [View("Расчет", new string[] {
            "Код as \'Код\'",
            "Дата as \'Дата\'",
            "Сотрудники.Фио as \'Фио\'",
            "Сотрудники.Должности.Наименование as \'Должность\'"})]
    public class Расчет : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private IIS.Kk.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (Расчет CustomMembers)

        // *** End programmer edit section *** (Расчет CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (Расчет.Дата CustomAttributes)

        // *** End programmer edit section *** (Расчет.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (Расчет.Дата Get start)

                // *** End programmer edit section *** (Расчет.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (Расчет.Дата Get end)

                // *** End programmer edit section *** (Расчет.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расчет.Дата Set start)

                // *** End programmer edit section *** (Расчет.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (Расчет.Дата Set end)

                // *** End programmer edit section *** (Расчет.Дата Set end)
            }
        }
        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Расчет.Код CustomAttributes)

        // *** End programmer edit section *** (Расчет.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Расчет.Код Get start)

                // *** End programmer edit section *** (Расчет.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Расчет.Код Get end)

                // *** End programmer edit section *** (Расчет.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расчет.Код Set start)

                // *** End programmer edit section *** (Расчет.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Расчет.Код Set end)

                // *** End programmer edit section *** (Расчет.Код Set end)
            }
        }
        
        /// <summary>
        /// Расчет.
        /// </summary>
        // *** Start programmer edit section *** (Расчет.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Расчет.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Kk.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Расчет.Сотрудники Get start)

                // *** End programmer edit section *** (Расчет.Сотрудники Get start)
                IIS.Kk.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Расчет.Сотрудники Get end)

                // *** End programmer edit section *** (Расчет.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расчет.Сотрудники Set start)

                // *** End programmer edit section *** (Расчет.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Расчет.Сотрудники Set end)

                // *** End programmer edit section *** (Расчет.Сотрудники Set end)
            }
        }
        
        // *** Start programmer edit section *** (Расчет.Отправить CustomAttributes)

        // *** End programmer edit section *** (Расчет.Отправить CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Отправить()
        {
            // *** Start programmer edit section *** (Расчет.Отправить method implementation)

            return;
            // *** End programmer edit section *** (Расчет.Отправить method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "Расчет" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Расчет
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Расчет", typeof(IIS.Kk.Расчет));
                }
            }
            
            /// <summary>
            /// "Расчет" view.
            /// </summary>
            public static ICSSoft.STORMNET.View Расчет2
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("Расчет", typeof(IIS.Kk.Расчет));
                }
            }
        }
    }
}
