//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kk
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудники.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудники CustomAttributes)

    // *** End programmer edit section *** (Сотрудники CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникиE", new string[] {
            "Код as \'Код\'",
            "Фио as \'Фио\'",
            "Отправлен as \'Отправлен\'",
            "Должности as \'Должности\'",
            "Должности.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Должности.Наименование"})]
    [MasterViewDefineAttribute("СотрудникиE", "Должности", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("СотрудникиL", new string[] {
            "Код as \'Код\'",
            "Фио as \'Фио\'",
            "Отправлен as \'Отправлен\'",
            "Должности.Наименование as \'Наименование\'"})]
    public class Сотрудники : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private string fФио;
        
        private bool fОтправлен = false;
        
        private IIS.Kk.Должности fДолжности;
        
        // *** Start programmer edit section *** (Сотрудники CustomMembers)

        // *** End programmer edit section *** (Сотрудники CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Код CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Код Get start)

                // *** End programmer edit section *** (Сотрудники.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (Сотрудники.Код Get end)

                // *** End programmer edit section *** (Сотрудники.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Код Set start)

                // *** End programmer edit section *** (Сотрудники.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (Сотрудники.Код Set end)

                // *** End programmer edit section *** (Сотрудники.Код Set end)
            }
        }
        
        /// <summary>
        /// Отправлен.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Отправлен CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Отправлен CustomAttributes)
        public virtual bool Отправлен
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Отправлен Get start)

                // *** End programmer edit section *** (Сотрудники.Отправлен Get start)
                bool result = this.fОтправлен;
                // *** Start programmer edit section *** (Сотрудники.Отправлен Get end)

                // *** End programmer edit section *** (Сотрудники.Отправлен Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Отправлен Set start)

                // *** End programmer edit section *** (Сотрудники.Отправлен Set start)
                this.fОтправлен = value;
                // *** Start programmer edit section *** (Сотрудники.Отправлен Set end)

                // *** End programmer edit section *** (Сотрудники.Отправлен Set end)
            }
        }
        
        /// <summary>
        /// Фио.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Фио CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Фио CustomAttributes)
        [StrLen(255)]
        public virtual string Фио
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Фио Get start)

                // *** End programmer edit section *** (Сотрудники.Фио Get start)
                string result = this.fФио;
                // *** Start programmer edit section *** (Сотрудники.Фио Get end)

                // *** End programmer edit section *** (Сотрудники.Фио Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Фио Set start)

                // *** End programmer edit section *** (Сотрудники.Фио Set start)
                this.fФио = value;
                // *** Start programmer edit section *** (Сотрудники.Фио Set end)

                // *** End programmer edit section *** (Сотрудники.Фио Set end)
            }
        }
        
        /// <summary>
        /// Сотрудники.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.Должности CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.Должности CustomAttributes)
        [PropertyStorage(new string[] {
                "Должности"})]
        [NotNull()]
        public virtual IIS.Kk.Должности Должности
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.Должности Get start)

                // *** End programmer edit section *** (Сотрудники.Должности Get start)
                IIS.Kk.Должности result = this.fДолжности;
                // *** Start programmer edit section *** (Сотрудники.Должности Get end)

                // *** End programmer edit section *** (Сотрудники.Должности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.Должности Set start)

                // *** End programmer edit section *** (Сотрудники.Должности Set start)
                this.fДолжности = value;
                // *** Start programmer edit section *** (Сотрудники.Должности Set end)

                // *** End programmer edit section *** (Сотрудники.Должности Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиE", typeof(IIS.Kk.Сотрудники));
                }
            }
            
            /// <summary>
            /// "СотрудникиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиL", typeof(IIS.Kk.Сотрудники));
                }
            }
        }
    }
}
